const fs = require('fs');
let code = fs.readFileSync('src/App.tsx', 'utf-8');

const newPresets = `const PRESETS = [
  {
    id: 'crimson-pulse',
    name: 'Crimson Symmetrical',
    description: 'A deep red symmetrical waveform against a pure black canvas with slow falling stars.',
    visuals: {
      style: 'symmetrical-waveform' as VisualizerStyle,
      primaryColor: '#cc1122',
      secondaryColor: '#ff3344',
      glowColor: '#ff0000',
      glowStrength: 10,
      lineThickness: 2,
      sensitivity: 1.2,
      fftSize: 1024,
      barRoundness: 0,
      barSpacing: 0,
      placement: 'center' as const,
    },
    particles: {
      type: 'stars' as ParticleType,
      count: 100,
      minSize: 1,
      maxSize: 3,
      speed: 0.5,
      color: '#ff3333',
      gravity: 0.5,
      wind: 0.1,
      beatReactive: true,
      beatThreshold: 140,
    },
    background: {
      type: 'color' as const,
      color: '#000000',
      gradientStart: '#000000',
      gradientEnd: '#000000',
      imageUrl: null,
      videoUrl: null,
      blur: 0,
      opacity: 1.0,
    },
    title: {
      visible: true,
      text: 'CRIMSON PULSE',
      artist: 'Audio Wave',
      fontSize: 48,
      color: '#ff3344',
      fontFamily: 'Space Grotesk' as const,
      position: 'bottom-right' as const,
      fadeIn: true,
    }
  },
  {
    id: 'cyberpunk-sunset',
    name: 'Cyberpunk Sunset',
    description: 'Neon magenta visuals, flying cyber triangles, and circular audio waveforms.',
    visuals: {
      style: 'circular' as VisualizerStyle,
      primaryColor: '#ff007f', // hot pink
      secondaryColor: '#00ffff', // neon cyan
      glowColor: '#ff007f',
      glowStrength: 15,
      lineThickness: 3,
      sensitivity: 1.2,
      fftSize: 1024,
      barRoundness: 4,
      barSpacing: 2,
      placement: 'center' as const,
    },
    particles: {
      type: 'cyber-triangles' as ParticleType,
      count: 60,
      minSize: 2,
      maxSize: 6,
      speed: 2,
      color: '#ffaa00',
      gravity: -0.5,
      wind: 1.5,
      beatReactive: true,
      beatThreshold: 130,
    },
    background: {
      type: 'gradient' as const,
      color: '#000000',
      gradientStart: '#1a0033',
      gradientEnd: '#000000',
      imageUrl: null,
      videoUrl: null,
      blur: 0,
      opacity: 0.9,
    },
    title: {
      visible: true,
      text: 'CYBERPUNK',
      artist: 'Synthwave Engine',
      fontSize: 56,
      color: '#00ffff',
      fontFamily: 'Outfit' as const,
      position: 'center' as const,
      fadeIn: true,
    }
  },
  {
    id: 'toxic-overdrive',
    name: 'Toxic Overdrive',
    description: 'Aggressive green and acid yellow digital bars with intense neon glow.',
    visuals: {
      style: 'digital-vu-blocks' as VisualizerStyle,
      primaryColor: '#00ff00',
      secondaryColor: '#ccff00',
      glowColor: '#00ff00',
      glowStrength: 25,
      lineThickness: 4,
      sensitivity: 1.6,
      fftSize: 1024,
      barRoundness: 2,
      barSpacing: 4,
      placement: 'center' as const,
    },
    particles: {
      type: 'bubbles' as ParticleType,
      count: 150,
      minSize: 2,
      maxSize: 5,
      speed: 3,
      color: '#ccff00',
      gravity: -1,
      wind: 0.2,
      beatReactive: true,
      beatThreshold: 140,
    },
    background: {
      type: 'color' as const,
      color: '#021000',
      gradientStart: '#001000',
      gradientEnd: '#0a1a05',
      imageUrl: null,
      videoUrl: null,
      blur: 0,
      opacity: 0.85,
    },
    title: {
      visible: true,
      text: 'TOXIC OVERDRIVE',
      artist: 'Acid Injection',
      fontSize: 54,
      color: '#00ff00',
      fontFamily: 'JetBrains Mono' as const,
      position: 'top-left' as const,
      fadeIn: true,
    }
  },
  {
    id: 'retro-80s-grid',
    name: 'Retro 80s Grid',
    description: 'Neon purple grid styling with ambient neon digital particles.',
    visuals: {
      style: 'retro' as VisualizerStyle,
      primaryColor: '#ff00ff',
      secondaryColor: '#00ffff',
      glowColor: '#ff00ff',
      glowStrength: 20,
      lineThickness: 3,
      sensitivity: 1.4,
      fftSize: 2048,
      barRoundness: 0,
      barSpacing: 0,
      placement: 'center' as const,
    },
    particles: {
      type: 'digital' as ParticleType,
      count: 100,
      minSize: 1,
      maxSize: 4,
      speed: 1.5,
      color: '#ff00ff',
      gravity: 0,
      wind: 2.0,
      beatReactive: true,
      beatThreshold: 130,
    },
    background: {
      type: 'gradient' as const,
      color: '#000000',
      gradientStart: '#2b00ff',
      gradientEnd: '#000000',
      imageUrl: null,
      videoUrl: null,
      blur: 2,
      opacity: 0.8,
    },
    title: {
      visible: true,
      text: 'RETRO 80S',
      artist: 'Vaporwave',
      fontSize: 60,
      color: '#00ffff',
      fontFamily: 'Space Grotesk' as const,
      position: 'top-right' as const,
      fadeIn: true,
    }
  },
  {
    id: 'sakura-petal-breeze',
    name: 'Sakura Petal Breeze',
    description: 'Gentle fresnel waves with drifting sakura petals over a dark violet canvas.',
    visuals: {
      style: 'fresnel-wave' as VisualizerStyle,
      primaryColor: '#ffb7c5',
      secondaryColor: '#ffffff',
      glowColor: '#ffb7c5',
      glowStrength: 12,
      lineThickness: 2,
      sensitivity: 1.0,
      fftSize: 2048,
      barRoundness: 0,
      barSpacing: 0,
      placement: 'center' as const,
    },
    particles: {
      type: 'sakura' as ParticleType,
      count: 80,
      minSize: 3,
      maxSize: 8,
      speed: 1.2,
      color: '#ffb7c5',
      gravity: 0.8,
      wind: 1.5,
      beatReactive: false,
      beatThreshold: 150,
    },
    background: {
      type: 'color' as const,
      color: '#1a0a1a',
      gradientStart: '#1a0a1a',
      gradientEnd: '#000000',
      imageUrl: null,
      videoUrl: null,
      blur: 0,
      opacity: 1.0,
    },
    title: {
      visible: true,
      text: 'SAKURA BREEZE',
      artist: 'Ambient Journey',
      fontSize: 42,
      color: '#ffb7c5',
      fontFamily: 'Inter' as const,
      position: 'bottom-left' as const,
      fadeIn: true,
    }
  },
  {
    id: 'monochromatic-wave',
    name: 'Monochromatic Wave',
    description: 'Sleek silver flowing wavelines and subtle dust sparkles over black canvas.',
    visuals: {
      style: 'waveform' as VisualizerStyle,
      primaryColor: '#ffffff',
      secondaryColor: '#aaaaaa',
      glowColor: '#ffffff',
      glowStrength: 5,
      lineThickness: 2.5,
      sensitivity: 1.1,
      fftSize: 2048,
      barRoundness: 0,
      barSpacing: 0,
      placement: 'center' as const,
    },
    particles: {
      type: 'dust' as ParticleType,
      count: 120,
      minSize: 0.5,
      maxSize: 2,
      speed: 0.2,
      color: '#ffffff',
      gravity: -0.1,
      wind: 0.1,
      beatReactive: false,
      beatThreshold: 150,
    },
    background: {
      type: 'color' as const,
      color: '#050505',
      gradientStart: '#000000',
      gradientEnd: '#000000',
      imageUrl: null,
      videoUrl: null,
      blur: 0,
      opacity: 1.0,
    },
    title: {
      visible: true,
      text: 'MINIMAL',
      artist: 'Monochrome',
      fontSize: 40,
      color: '#ffffff',
      fontFamily: 'Inter' as const,
      position: 'center' as const,
      fadeIn: true,
    }
  },
  {
    id: 'nebula-mountain-matrix',
    name: 'Nebula Mountain Matrix',
    description: 'Cosmic purple wave matrix with stardust nebula particles.',
    visuals: {
      style: 'wave-matrix' as VisualizerStyle,
      primaryColor: '#8a2be2',
      secondaryColor: '#4b0082',
      glowColor: '#8a2be2',
      glowStrength: 18,
      lineThickness: 2,
      sensitivity: 1.3,
      fftSize: 1024,
      barRoundness: 0,
      barSpacing: 2,
      placement: 'center' as const,
    },
    particles: {
      type: 'dust' as ParticleType,
      count: 200,
      minSize: 1,
      maxSize: 3,
      speed: 0.4,
      color: '#8a2be2',
      gravity: -0.2,
      wind: 0.5,
      beatReactive: true,
      beatThreshold: 120,
    },
    background: {
      type: 'gradient' as const,
      color: '#000000',
      gradientStart: '#000000',
      gradientEnd: '#1a0033',
      imageUrl: null,
      videoUrl: null,
      blur: 5,
      opacity: 0.9,
    },
    title: {
      visible: true,
      text: 'NEBULA MATRIX',
      artist: 'Deep Space',
      fontSize: 50,
      color: '#d8b4fe',
      fontFamily: 'Outfit' as const,
      position: 'top-left' as const,
      fadeIn: true,
    }
  },
  {
    id: 'synthwave-horizon',
    name: 'Synthwave Horizon',
    description: 'Vaporwave sunset colors intersecting with dynamic laser beams.',
    visuals: {
      style: 'cyber-laser-horizon' as VisualizerStyle,
      primaryColor: '#ff0055',
      secondaryColor: '#00d0ff',
      glowColor: '#ff0055',
      glowStrength: 18,
      lineThickness: 2,
      sensitivity: 1.5,
      fftSize: 2048,
      barRoundness: 0,
      barSpacing: 2,
      placement: 'center' as const,
    },
    particles: {
      type: 'spark-stars' as ParticleType,
      count: 100,
      minSize: 2,
      maxSize: 6,
      speed: 2.5,
      color: '#ffaa00',
      gravity: -0.5,
      wind: -0.5,
      beatReactive: true,
      beatThreshold: 130,
    },
    background: {
      type: 'gradient' as const,
      color: '#10051a',
      gradientStart: '#000010',
      gradientEnd: '#2a003a',
      imageUrl: null,
      videoUrl: null,
      blur: 2,
      opacity: 0.8,
    },
    title: {
      visible: true,
      text: 'SYNTH HORIZON',
      artist: 'Neon Nostalgia',
      fontSize: 48,
      color: '#00d0ff',
      fontFamily: 'Outfit' as const,
      position: 'bottom-right' as const,
      fadeIn: true,
    }
  }
];`;

const startIdx = code.indexOf('const PRESETS = [');
const endIdx = code.indexOf('];', startIdx);

if (startIdx !== -1 && endIdx !== -1) {
  code = code.substring(0, startIdx) + newPresets + code.substring(endIdx + 2);
  fs.writeFileSync('src/App.tsx', code);
  console.log('Done patching presets');
} else {
  console.log('Could not find PRESETS');
}
